namespace: ansible
name: misc
version: 1.0.0
readme: README.md
authors: null
description: null
license: null
license_file: null
tags: null
dependencies:
  ansible.amazon: '>=1.0'
  ansible.netcommon: '>=1.0'
  ansible.windows: '>=1.0'
  ansible.unix: '>=1.0'
repository: git@github.com:coll-test/ansible.misc.git
documentation: https://github.com/coll-test/ansible.misc/tree/master/docs
homepage: https://github.com/coll-test/ansible.misc
issues: https://github.com/coll-test/ansible.misc/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
